name: physical_param
description: Библиотека для работы с физическими параметрами
version: 1.0.0
repository: https://github.com/ProfAndroid2020/physical_param

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
